### ISSUE TITLE
FIXME:: from events file, passing in children part which is JSX

### ISSUE THREAD

**Issue by saurshaz** [applerdotxyz/rn-composable-ui#14]
FIXME:: from events file, passing in children part which is JSX

![104809143-1bdba580-5811-11eb-96ca-574f3d6889e1](https://user-images.githubusercontent.com/1283920/105968178-c1620500-60ac-11eb-81b0-c5ccdca3ef63.png)

**Comment by saurshaz** [comment]
@sagar0211 
test that this is doable from
1. config file
2. setAppState
and
3. setLayoutConfig

**Comment by sagar0211** [comment]
This has been tested @saurshaz 
Reference
https://github.com/applerdotxyz/rn-config-tyler/blob/tailwind-layout/packages/demo/examples/with-setLayout/layout.js
