### ISSUE TITLE
build examples for functional atleast 2-3 interaction flows

### ISSUE THREAD

**Issue by saurshaz** [applerdotxyz/rn-composable-ui#20]
Multiple examples in `examples` folder now

**Comment by sagar0211** [comment]
3-4 screen web
![Screenshot from 2021-02-06 15-02-38](https://user-images.githubusercontent.com/44940025/107114633-5cb56000-688d-11eb-8d3f-f49940a6abdb.png)
![Screenshot from 2021-02-06 15-02-41](https://user-images.githubusercontent.com/44940025/107114636-5f17ba00-688d-11eb-8d0d-c76abf507d43.png)
![Screenshot from 2021-02-06 15-02-48](https://user-images.githubusercontent.com/44940025/107114638-6048e700-688d-11eb-90a5-ac24289c91fb.png)
![Screenshot from 2021-02-06 15-02-51](https://user-images.githubusercontent.com/44940025/107114639-60e17d80-688d-11eb-9e8e-d1aa30fe3506.png)

**Comment by sagar0211** [comment]
![s1](https://user-images.githubusercontent.com/44940025/107204435-ae432380-6a22-11eb-8f1a-5acaae9264e4.png)
![s2](https://user-images.githubusercontent.com/44940025/107204439-af745080-6a22-11eb-9cd7-6d7eae27e01e.png)
![s3](https://user-images.githubusercontent.com/44940025/107204444-b00ce700-6a22-11eb-90b6-6db487b7de0e.png)
![s4](https://user-images.githubusercontent.com/44940025/107204473-b69b5e80-6a22-11eb-981e-e645fddea5e1.png)
![s5](https://user-images.githubusercontent.com/44940025/107204477-b733f500-6a22-11eb-892a-140e6d59a59f.png)

**Comment by saurshaz** [comment]
@subhamtsd  adding for *todo* example
