### ISSUE TITLE
automate a test to test all config examples

### ISSUE THREAD

**Issue by saurshaz** [applerdotxyz/rn-composable-ui#44]
cypress or seleniumbase

**Comment by saurshaz** [comment]
using cypress /puppeteer we shall be able to achieve this.

we will pass in the attributes and start testing through an alternate index.js (which could be like index.js) but only takes in one config values at a time

**Comment by sagar0211** [comment]
- [ ] 3_4-screen-example-mobile
- [ ] 3_4-screen-example-web

- [ ] another-grid

- [ ] app-one

- [ ] app-three

- [ ] app-two

  

- [ ] collapsible-leftnav

  

- [ ] component-mount

  

- [ ] dashboard-demo

 

- [ ] dynamic-navigation

  

- [ ] react-router-port

  

- [ ] todo-app

  

- [ ] vanilla-grid-layout

  

- [ ] with-appstate

  

- [ ] with-calendar

  

- [ ] with-charts

  

- [ ] with-jsonforms

  

- [ ] with-setLayout

  

- [ ] with-setLayout (without hide)

  

- [ ] with-tailwind

**Comment by sagar0211** [comment]
creating new issue for to-do

**Comment by sagar0211** [comment]
https://github.com/applerdotxyz/rn-composable-ui/tree/e2e-testing --testing branch
https://github.com/applerdotxyz/rn-composable-ui/blob/e2e-testing/.github/workflows/main.yml -- github action workflow
https://github.com/applerdotxyz/rn-composable-ui/tree/e2e-testing/cypress --testing  code is in integration folder
