### ISSUE TITLE
a runtime switch capability to switch through various available examples

### ISSUE THREAD

**Issue by saurshaz** [applerdotxyz/rn-composable-ui#45]
a dropdown shows all examples, and the one we select and submit gets opened in a new screen
This could be good demo, which we can then test with #44

**Comment by saurshaz** [comment]
I think this can be closed now.
test latest from `develop` branch and close if current one looks good
@sagar0211

**Comment by sagar0211** [comment]
![Screenshot from 2021-03-09 13-06-00](https://user-images.githubusercontent.com/44940025/110434924-67575500-80d8-11eb-9b1d-236e72aefdba.png)
