### ISSUE TITLE
create a layout using tailwind components

### ISSUE THREAD

**Issue by saurshaz** [applerdotxyz/rn-composable-ui#49]
https://tailwindcomponents.com/components

**Comment by sagar0211** [comment]
![Screenshot from 2021-03-09 13-02-38](https://user-images.githubusercontent.com/44940025/110434637-12b3da00-80d8-11eb-900c-a7f2580f3a19.png)

**Comment by sagar0211** [comment]
References for tailwind 
@saurshaz

https://github.com/applerdotxyz/rn-config-tyler/blob/tailwind-layout/packages/demo/components/TailwindForm.tsx -- Tailwind Form CSS

https://github.com/applerdotxyz/rn-config-tyler/tree/tailwind-layout/packages/demo/examples/with-tailwind --layout config
