### ISSUE TITLE
getInitEvents, routes should not be compulsory for config

### ISSUE THREAD

**Issue by sagar0211** [applerdotxyz/rn-composable-ui#60]

**Comment by sagar0211** [comment]
https://github.com/applerdotxyz/rn-config-tyler/blob/tailwind-layout/packages/demo/examples/with-appstate/layout.js -- reference 

added empty route as 
`routes.routeOne = {}; `
if we remove this then while rendering it is displaying as Loading on screen

**Comment by saurshaz** [comment]
Fixed @sagar0211 try app-one
